name: dialyzer

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  dialyze:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:22.3.3-alpine-3.11.3
    steps:
    - name: Get elixir source code
      uses: actions/checkout@v2
      with:
        repository: elixir-lang/elixir

    - name: Install make
      run: apk add --no-cache make
    
    - name: Compile elixir
      run: make compile

    - name: Install deps needed for testing elixir
      run: apk add --no-cache git

    - name: Test elixir
      run: make test
      continue-on-error: true

    - name: Handle dialyzer PLT file caching
      id: cache-plt
      uses: actions/cache@v1
      with:
        path: .elixir.plt
        key: erlang:22.3.3-alpine-3.11.3

    - name: Create the dialyzer PLT file
      if: steps.cache-plt.outputs.cache-hit != 'true'
      run: make build_plt

    - name: Run dialyzer
      run: dialyzer -pa lib/elixir/ebin --plt .elixir.plt --fullpath lib/*/ebin
