name: dialyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  dialyze:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:22.3.3-alpine-3.11.3
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get elixir source code
      uses: actions/checkout@v2
      with:
        repository: elixir-lang/elixir
        path: elixir

    - name: Install make and deps needed for testing elixir
      run: apk add --no-cache make git
    
    - name: Compile elixir
      run: |
        cd elixir
        make compile
        cd ../

    - name: Test elixir
      run: |
        cd elixir
        make test
        cd ../
      continue-on-error: true

    - name: Handle dialyzer PLT file caching
      id: cache-plt
      uses: actions/cache@v1
      with:
        path: plt-dir
        key: erlang:22.3.3-alpine-3.11.3

    - name: Create the dialyzer PLT file
      if: steps.cache-plt.outputs.cache-hit != 'true'
      run: |
        cd elixir
        make build_plt
        mv .elixir.plt ../plt-dir
        cd ../

    - name: Run dialyzer
      run: elixir/bin/elixir dialyze.exs
