name: dialyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dialyze:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:22.3.3-alpine-3.11.3
    steps:
    - uses: actions/checkout@v2
      with:
        repository: elixir-lang/elixir

    - name: Install make
      run: apk add --no-cache make
    
    - name: Compile elixir
      run: make compile

    - name: Test elixir
      run: make test

    - name: Create the dialyzer PLT file
      run: make plt

    - name: Run dialyzer
      run: dialyzer -pa lib/elixir/ebin --plt .elixir.plt --fullpath lib/*/ebin